apiVersion: v1
kind: Pod
metadata:
  name: nginx-stable
  namespace: expense
  labels:
    course: k8
    trainer: sivakumar
spec:
  containers:
  - name: nginx-stable
    image: nginx:stable-otel
    namespace: expense
  - name: alma
    image: almalinux:9
    command: ["sleep","2000"]
    namespace: expense